### ISSUE TITLE
question about the todo comment

### ISSUE THREAD

**Issue by lucianidev** [theritikchoure/carrierjs#10]
Good evening,

I would like to contribute to this project. In the main file there are commonly repeated lines:
`req.onreadystatechange = () => {
                    if(req.readyState === 4 && req.status === 404) {
                        // TODO
                    }
                }
`

Can you explain what the todo means.

Thanks for your attention,
lucianidev

**Comment by theritikchoure** [comment]
We were supposed to do error handling from there, but now we are not using this block for error handling. 

we have removed it. 

Thanks for your issue.

**Comment by theritikchoure** [comment]
A heartfelt thanks to you for your contribution to this project 🎉🎉

We are really grateful for your contribution.

**Happy Learning 💚!!!**
