### ISSUE TITLE
Setup the testing feature for the library

### ISSUE THREAD

**Issue by theritikchoure** [theritikchoure/carrierjs#11]
Want unit testing feature, if you know how to implement, you can do it.

**Comment by tamalchowdhury** [comment]
I was thinking about it the other day. I would like to give it a shot by adding Jest testing feature.

**Comment by theritikchoure** [comment]
@tamalchowdhury thanks, man. I really need help setting up testing.

**Comment by tamalchowdhury** [comment]
Hi Ritik, I looked into the code today. I saw you already added the `test` files. I thought about adding tests for `isEven` and other functions, but I see they are not exported. 

Also, I don't have much knowledge of making tests with functions that interact with the API, so I am a bit challanged as well.
