### ISSUE TITLE
Add "Thanks To All Contributors" section at the last of readme file

### ISSUE THREAD

**Issue by theritikchoure** [theritikchoure/carrierjs#14]
Add the ```Thanks To All Contributors``` section at the last of the readme file, which should look like the below screenshot.

![image](https://user-images.githubusercontent.com/56495602/196401557-6fc9eed3-f4ea-439f-b4ab-6937c6b69dbb.png)

### ⚠️ Important Message 

 No need to wait for assigning, you can raise the pull request.

**Comment by Pragya2056** [comment]
#15 
the issue was looked upon

**Comment by Pragya2056** [comment]
@theritikchoure 
please review it
