### ISSUE TITLE
Add Twitter follow badge in readme file

### ISSUE THREAD

**Issue by theritikchoure** [theritikchoure/carrierjs#16]
Add Twitter follow badge in the readme file and add the following URL to reference. 

```https://twitter.com/carrier_js```

ℹ️ Twitter follow badge should look like this 👇
![image](https://user-images.githubusercontent.com/56495602/196408662-b0840d6c-4c34-4248-83e3-fe40703bb60f.png)

ℹ️ Add twitter follow along with below badges
![image](https://user-images.githubusercontent.com/56495602/196408981-9ab39cca-839b-4e3e-8cd1-39bbb5ad95f3.png)

#### ⚠️ Important Message
No need to wait for assigning, you can raise the pull request.

**Comment by najeebkp** [comment]
hi @theritikchoure please assign this to me

**Comment by pratyushkr11** [comment]
Hello @theritikchoure assign this issue to me.

**Comment by theritikchoure** [comment]
@najeebkp @pratyushkr11 

⚠️ Important Message

No need to wait for assigning, you can raise the pull request.

Give a ⭐ to this repo.
