### ISSUE TITLE
Add Contributors name in the /doc/contributors.html file

### ISSUE THREAD

**Issue by theritikchoure** [theritikchoure/carrierjs#23]
Add all contributor's names in the /doc/contributors.html file along with their GitHub profile link.

### ⚠️ Important Message
No need to wait for assigning, you can raise the pull request.

**Comment by amanaggarwal06** [comment]
Hey, Can you please explain this issue to me?

**Comment by theritikchoure** [comment]
Inside the ```docs``` folder there is a file called ```contributors.html```.

Inside that file, we want to add the names of all contributors along with their github profile link.

**Comment by amanaggarwal06** [comment]
Okay, I'll add and then I will get back to you.

**Comment by theritikchoure** [comment]
@SattyamSamania 

### ⚠️ Important Message
No need to wait for assigning, you can raise the pull request.
