### ISSUE TITLE
Add animated hero section for /docs/index.html page

### ISSUE THREAD

**Issue by theritikchoure** [theritikchoure/carrierjs#39]
![image](https://user-images.githubusercontent.com/56495602/198274716-ee3d5f72-f786-4e91-aff2-9bef17505f37.png)

Change this simple background with the animated background like this 👇

https://codepen.io/alvarotrigo/pen/GRvYNax

**⚠️ Note:** Use background colors related to the theme.

Comment if you need any help or information.

**Comment by IM-TECHNO** [comment]
Assign me ! I'll contribute !
