### ISSUE TITLE
Contributors Page Not Working Properly in Documentation

### ISSUE THREAD

**Issue by devXprite** [theritikchoure/carrierjs#46]
**Describe the bug**
I am trying to view the Contributors page in the [documentation](https://github.com/theritikchoure/carrierjs/issues), but it keeps showing the "Loading" message and never actually loads the page. I have tried accessing the page from different browsers and devices, but the issue persists.

**To Reproduce**
1. Go to the documentation for the project.
2. Navigate to the Contributors page.
3. Observe that the page never loads and displays the "Loading" message indefinitely.

**Screenshots**
I have included a screenshot of the issue below:
![Screenshot](https://user-images.githubusercontent.com/80192140/211139230-6adddcb2-912c-4ff1-8feb-6226c78ceecd.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

**Additional context**
I want to work on this Issue.

**Comment by theritikchoure** [comment]
Thank you @devXprite 

It is fixed now, can you check it and let me know

**Comment by devXprite** [comment]
Now its Working fine :+1: 
But i think Profile Pic in dark theme not looks good:

![cr2](https://user-images.githubusercontent.com/80192140/211140293-12c2cffd-9054-4203-bb37-5bd483452a35.png)

**Comment by theritikchoure** [comment]
if you know how to fix it then take your time and fix it.
if not then you can raise an issue

**Comment by devXprite** [comment]
> if you know how to fix it then take your time and fix it. if not then you can raise an issue

Yes, I can fix it.
