### ISSUE TITLE
Add Open Graph Tag in Documentation Site

### ISSUE THREAD

**Issue by theritikchoure** [theritikchoure/carrierjs#5]
add open graph meta tags inside the ```<head>``` tag. [Open Graph](https://ogp.me/) meta tags help users optimize their social media link previews, so users always see the essential information. To know more about open graph read this amazing blog post → [What is Open Graph and how can I use it for my website?](https://www.freecodecamp.org/news/what-is-open-graph-and-how-can-i-use-it-for-my-website/).

Suggest Solution
The banner image is already uploaded inside the ```doc/assets/image``` folder with the name ```CarrierJs.png```

Add its path to the meta tag of property ```og:image```.

```js
<meta property="og:title" content="CarrierJs - Promise based HTTP client with ultimate caching">
<meta property="og:site_name" content="CarrierJs - Promise based HTTP client with ultimate caching">
<meta property="og:url" content="https://theritikchoure.github.io/carrierjs/doc/">
<meta property="og:description" content="Carrier JS is promise based http client for browsers. It is used to interact with servers with the ultimate caching feature. You can retrieve data from a URL without having to do a full page refresh.">
<meta property="og:type" content="website">
<meta property="og:image" content="add link to the banner image here...">
```

**Comment by theritikchoure** [comment]
Use below link for ```og:image```

```https://theritikchoure.github.io/carrierjs/doc/assets/images/Carrier.Js.png```

**Comment by tamalchowdhury** [comment]
Hi @theritikchoure I would like to take this issue if not taken by someone else.

**Comment by theritikchoure** [comment]
Hii @tamalchowdhury, I have assigned you this issue
