### ISSUE TITLE
Remove Guides Section from README

### ISSUE THREAD

**Issue by theritikchoure** [theritikchoure/carrierjs#50]
### Issue Description

The README file currently contains a "Guides" section, which we no longer need. This section should be removed to streamline the documentation.

### Task

- [ ] Remove the "Guides" section from the README file.
- [ ] Update the table of contents to reflect the changes.

### Contribution Guidelines

- Fork this repository.
- Create a branch for this issue.
- Make the necessary changes.
- Create a pull request referencing this issue.

Feel free to ask for help or clarification if needed. This is a great opportunity for first-time contributors!

**Comment by aditya7302** [comment]
please assign this issue to me.

**Comment by Abhishekgupta204** [comment]
Please assign this issue to me.

**Comment by theritikchoure** [comment]
@aditya7302 assigned to you

**Comment by theritikchoure** [comment]
@aditya7302 Thanks for your contributions, please give a ⭐ to this repo so that it will react to more developers.
